### ISSUE TITLE
Pluto.jl to be added to comparison section?

### ISSUE THREAD

**Issue by jcmkk3** [herbps10/Reactor#2]
You may already be familiar with it, but there has recently been a similarly inspired (Observable) tool released for Julia called [Pluto.jl](https://github.com/fonsp/Pluto.jl). I don't use Julia, but from the outside, it looks like a really slick implementation of the paradigm.

**Comment by herbps10** [comment]
Thanks for the heads up, I hadn't seen it before, it indeed looks slick. Added it to the comparison section. I like their file saving format, I'd like to implement something similar for Reactor (right now notebooks are saved as Rds files, but I'd like to switch it to use plain text files.)
